on:
  push:
  pull_request:
    branches: [ master ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - uses: actions/setup-go@v2
      with:
        go-version: ^1.14

    - uses: actions/checkout@v2

    - run: go test -v -coverprofile=cover.out

    - uses: codecov/codecov-action@v1.0.6
