name: Test

on:
  push:
  pull_request:
    branches: [ master ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: staticcheck
      uses: reviewdog/action-staticcheck@v1
      with:
        reporter: github-check

    - uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - run: go test -v -coverprofile=cover.out

    - uses: codecov/codecov-action@v1
